[package]
name = "nettu_scheduler_domain"
version = "0.2.1"
description = "Nettu scheduler domain"
license = "MIT"
authors = ["Fredrik Meringdal"]
edition = "2018"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nettu_scheduler_utils = { path = "../utils", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
rrule = "0.5.8"
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = { version = "0.5.3", features = ["serde"] }
anyhow = "1.0.0"
url = "2.2.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
jsonwebtoken = "7"
thiserror = "1.0"
itertools = "0.10.1"
rand = "0.8.4"
tracing = "0.1.25"
