// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountWebhookSettingsDTO } from "./AccountWebhookSettingsDTO";

export type AccountSettingsDTO = { webhook: AccountWebhookSettingsDTO | null, };
