// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationProvider } from "./IntegrationProvider";

export type AddAccountIntegrationRequestBody = { clientId: string, clientSecret: string, redirectUri: string, provider: IntegrationProvider, };
