// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";

export type BusyCalendarProvider = { "provider": "Google", "id": string } | { "provider": "Outlook", "id": string } | { "provider": "Nittei", "id": ID };
