// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEventReminder } from "./CalendarEventReminder";
import type { CalendarEventStatus } from "./CalendarEventStatus";
import type { ID } from "./ID";
import type { RRuleOptions } from "./RRuleOptions";

export type CalendarEvent = { id: ID, parent_id: string | null, title: string | null, description: string | null, location: string | null, all_day: boolean, status: CalendarEventStatus, start_time: string, duration: bigint, busy: boolean, end_time: string, created: bigint, updated: bigint, recurrence: RRuleOptions | null, exdates: Array<string>, calendar_id: ID, user_id: ID, account_id: ID, reminders: Array<CalendarEventReminder>, service_id: ID | null, metadata: Record<string, string>, };
