// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";

export type CreateUserRequestBody = { metadata?: Record<string, string>, userId: ID | null, };
