// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCalendarRequestBody = { timezone: string, weekStart?: string, metadata?: Record<string, string>, };
