// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Occurrence of a `CalendarEvent`
 */
export type EventInstance = { startTime: string, endTime: string, busy: boolean, };
