// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarDTO } from "./CalendarDTO";
import type { EventWithInstancesDTO } from "./EventWithInstancesDTO";

export type GetCalendarEventsAPIResponse = { calendar: CalendarDTO, events: Array<EventWithInstancesDTO>, };
