// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEventDTO } from "./CalendarEventDTO";
import type { EventInstance } from "./EventInstance";

export type GetEventInstancesAPIResponse = { event: CalendarEventDTO, instances: Array<EventInstance>, };
