// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";

export type GetEventsByCalendarsQueryParams = { calendarIds: Array<ID> | null, startTime: Date, endTime: Date, };
