// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventInstance } from "./EventInstance";

export type GetUserFreeBusyAPIResponse = { busy: Array<EventInstance>, userId: string, };
