// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RRuleFrequency } from "./RRuleFrequency";
import type { WeekDay } from "./WeekDay";

/**
 * Options for recurring events
 */
export type RRuleOptions = { freq: RRuleFrequency, interval: number, count?: number, until?: string, bysetpos?: Array<number>, byweekday?: Array<WeekDay>, bymonthday?: Array<number>, bymonth?: Array<string>, byyearday?: Array<number>, byweekno?: Array<number>, };
