// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";
import type { ScheduleRule } from "./ScheduleRule";

export type ScheduleDTO = { id: ID, userId: ID, rules: Array<ScheduleRule>, timezone: string, metadata: Record<string, string>, };
