// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";
import type { TimePlan } from "./TimePlan";

export type ServiceResourceDTO = { userId: ID, serviceId: ID, availability: TimePlan, bufferAfter: bigint, bufferBefore: bigint, closestBookingTime: bigint, furthestBookingTime: bigint | null, };
