// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";

/**
 * A type that describes a time plan and is either a `Calendar` or a `Schedule`
 */
export type TimePlan = { "variant": "Calendar", "id": ID } | { "variant": "Schedule", "id": ID } | { "variant": "Empty" };
