// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountDTO } from "./AccountDTO";

/**
 * Account response object
 */
export type AccountResponse = { 
/**
 * Account retrieved
 */
account: AccountDTO, };
