// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSettingsDTO } from './AccountSettingsDTO'
import type { ID } from './ID'
import type { PEMKey } from './PEMKey'

/**
 * Account - an account can have multiple users
 */
export type AccountDTO = {
  /**
   * The unique identifier for the account
   */
  id: ID
  /**
   * Optional public key for JWT verification
   */
  publicJwtKey?: PEMKey
  /**
   * Account settings
   */
  settings: AccountSettingsDTO
}
