// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEventDTO } from './CalendarEventDTO'

export type AccountEventRemindersDTO = {
  event: CalendarEventDTO
  identifier: string
}
