// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Account webhook settings
 */
export type AccountWebhookSettingsDTO = { 
/**
 * Webhook URL
 */
url: string, 
/**
 * Webhook key
 */
key: string, };
