// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEventDTO } from './CalendarEventDTO'

/**
 * Account event reminders DTO
 */
export type AccountEventRemindersDTO = {
  /**
   * Calendar event
   */
  event: CalendarEventDTO
  /**
   * Identifier of the reminder
   */
  identifier: string
}
