// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BusyCalendarProvider } from './BusyCalendarProvider'

export type AddBusyCalendarRequestBody = { busy: BusyCalendarProvider }
