// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'
import type { IntegrationProvider } from './IntegrationProvider'

export type AddSyncCalendarRequestBody = {
  provider: IntegrationProvider
  calendarId: ID
  extCalendarId: string
}
