// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'
import type { IntegrationProvider } from './IntegrationProvider'

/**
 * Request body for adding a sync calendar
 */
export type AddSyncCalendarRequestBody = {
  /**
   * Integration provider
   * E.g. Google, Outlook, etc.
   */
  provider: IntegrationProvider
  /**
   * Calendar UUID to sync to
   */
  calendarId: ID
  /**
   * External calendar ID
   */
  extCalendarId: string
}
