// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'
import type { TimePlan } from './TimePlan'

export type AddUserToServiceRequestBody = {
  userId: ID
  availability?: TimePlan
  bufferAfter?: number
  bufferBefore?: number
  closestBookingTime?: number
  furthestBookingTime?: number
}
