// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar settings
 */
export type CalendarSettingsDTO = { 
/**
 * Week start day
 */
weekStart: string, 
/**
 * Timezone (e.g. "America/New_York")
 */
timezone: string, };
