// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEventReminder } from './CalendarEventReminder'
import type { CalendarEventStatus } from './CalendarEventStatus'
import type { ID } from './ID'
import type { RRuleOptions } from './RRuleOptions'
import type { JsonValue } from './serde_json/JsonValue'

/**
 * Calendar event object
 */
export type CalendarEventDTO = {
  /**
   * UUID of the event
   */
  id: ID
  /**
   * Optional title of the event
   */
  title: string | null
  /**
   * Optional description of the event
   */
  description: string | null
  /**
   * Optional type of the event
   * e.g. "meeting", "reminder", "birthday"
   */
  eventType: string | null
  /**
   * Optional location of the event
   */
  location: string | null
  /**
   * Flag to indicate if the event is all day, default is false
   */
  allDay: boolean
  /**
   * Status of the event, default is tentative
   */
  status: CalendarEventStatus
  /**
   * Optional parent event ID
   */
  externalParentId: string | null
  /**
   * Optional external ID
   */
  externalId: string | null
  /**
   * Start time of the event (UTC)
   */
  startTime: Date
  /**
   * Start time of the event (UTC)
   */
  endTime: Date
  /**
   * Duration of the event in milliseconds
   */
  duration: number
  /**
   * Busy flag
   */
  busy: boolean
  /**
   * Last updated timestamp (UTC)
   */
  updated: Date
  /**
   * Created tiemstamp (UTC)
   */
  created: Date
  /**
   * Recurrence rule
   */
  recurrence?: RRuleOptions
  /**
   * List of exclusion dates for the recurrence rule
   */
  exdates: Array<Date>
  /**
   * Optional recurring event ID
   * This is the ID of the recurring event that this event is part of
   * Default is None
   */
  recurringEventId: ID | null
  /**
   * Optional original start time of the event
   * This is the original start time of the event before it was moved (only for recurring events)
   * Default is None
   */
  originalStartTime: Date
  /**
   * UUID of the calendar
   */
  calendarId: ID
  /**
   * UUID of the user
   */
  userId: ID
  /**
   * List of reminders
   */
  reminders: Array<CalendarEventReminder>
  /**
   * Metadata (e.g. {"key": "value"})
   */
  metadata?: JsonValue
}
