// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum used for know which sort to use when searching events
 */
export type CalendarEventSort =
  | 'startTimeAsc'
  | 'startTimeDesc'
  | 'endTimeAsc'
  | 'endTimeDesc'
  | 'createdAsc'
  | 'createdDesc'
