// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarDTO } from "./CalendarDTO";

/**
 * Calendar object
 */
export type CalendarResponse = { 
/**
 * Calendar retrieved
 */
calendar: CalendarDTO, };
