// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarSettingsDTO } from './CalendarSettingsDTO'
import type { ID } from './ID'

export type CalendarDTO = {
  id: ID
  userId: ID
  settings: CalendarSettingsDTO
  metadata: Record<string, string>
}
