// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarSettingsDTO } from './CalendarSettingsDTO'
import type { ID } from './ID'

/**
 * Calendar object
 */
export type CalendarDTO = {
  /**
   * UUID of the calendar
   */
  id: ID
  /**
   * UUID of the user that owns the calendar
   */
  userId: ID
  /**
   * Calendar settings
   */
  settings: CalendarSettingsDTO
  /**
   * Metadata (e.g. {"key": "value"})
   */
  metadata: Record<string, string>
}
