// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEventReminder } from './CalendarEventReminder'
import type { CalendarEventStatus } from './CalendarEventStatus'
import type { ID } from './ID'
import type { RRuleOptions } from './RRuleOptions'
import type { JsonValue } from './serde_json/JsonValue'

/**
 * Request body for creating an event
 */
export type CreateEventRequestBody = {
  /**
   * UUID of the calendar where the event will be created
   */
  calendarId: ID
  /**
   * Optional title of the event
   */
  title?: string
  /**
   * Optional description of the event
   */
  description?: string
  /**
   * Optional type of the event
   * e.g. "meeting", "reminder", "birthday"
   * Default is None
   */
  eventType?: string
  /**
   * Optional parent event ID
   * This is useful for external applications that need to link Nittei's events to a wider data model (e.g. a project, an order, etc.)
   * Example: If the event is a meeting, the parent ID could be the project ID (ObjectId, UUID or any other string)
   */
  externalParentId?: string
  /**
   * Optional external event ID
   * This is useful for external applications that need to link Nittei's events to their own data models
   * Example: If the event is a meeting, the external ID could be the meeting ID in the external system
   *
   * Note that nothing prevents multiple events from having the same external ID
   * This can also be a way to link events together
   */
  externalId?: string
  /**
   * Optional location of the event
   */
  location?: string
  /**
   * Optional status of the event
   * Default is "Tentative"
   */
  status?: CalendarEventStatus
  /**
   * Optional flag to indicate if the event is an all day event
   * Default is false
   */
  allDay?: boolean
  /**
   * Start time of the event (UTC)
   */
  startTime: Date
  /**
   * Duration of the event in milliseconds
   */
  duration: number
  /**
   * Optional flag to indicate if the event is busy
   * Default is false
   */
  busy?: boolean
  /**
   * Optional recurrence rule
   */
  recurrence?: RRuleOptions
  /**
   * Optional list of exclusion dates for the recurrence rule
   */
  exdates?: Array<Date>
  /**
   * Optional recurring event ID
   * This is the ID of the recurring event that this event is part of
   * Default is None
   */
  recurringEventId?: ID
  /**
   * Optional original start time of the event
   * This is the original start time of the event before it was moved (only for recurring events)
   * Default is None
   */
  originalStartTime?: Date
  /**
   * Optional list of reminders
   */
  reminders?: Array<CalendarEventReminder>
  /**
   * Optional service UUID
   * This is automatically set when the event is created from a service
   */
  serviceId?: ID
  /**
   * Optional metadata (e.g. {"key": "value"})
   */
  metadata?: JsonValue
  /**
   * Optional created date
   * Defaults to the current date and time
   */
  created?: Date
  /**
   * Optional updated date
   * Defaults to the current date and time
   */
  updated?: Date
}
