// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEventReminder } from './CalendarEventReminder'
import type { CalendarEventStatus } from './CalendarEventStatus'
import type { ID } from './ID'
import type { RRuleOptions } from './RRuleOptions'

export type CreateEventRequestBody = {
  calendarId: ID
  title?: string
  description?: string
  parentId?: string
  location?: string
  status?: CalendarEventStatus
  allDay?: boolean
  startTime: Date
  duration: number
  busy?: boolean
  recurrence?: RRuleOptions
  reminders?: Array<CalendarEventReminder>
  serviceId?: ID
  metadata?: Record<string, string>
}
