// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'

/**
 * Request body for creating a user
 */
export type CreateUserRequestBody = {
  /**
   * Optional metadata (e.g. {"key": "value"})
   */
  metadata?: Record<string, string>
  /**
   * Optional user ID
   * If not provided, a new UUID will be generated
   * This is useful for external applications that need to link Nittei's users to their own data models
   */
  userId: ID | null
}
