// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for creating a calendar
 */
export type CreateCalendarRequestBody = {
  /**
   * Timezone for the calendar (e.g. "America/New_York")
   */
  timezone: string
  /**
   * Weekday for the calendar
   * Default is Monday
   */
  weekStart?: string
  name?: string
  key?: string
  /**
   * Optional metadata (e.g. {"key": "value"})
   */
  metadata?: Record<string, string>
}
