// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'

export type CreateServiceEventIntendRequestBody = {
  hostUserIds: Array<ID> | null
  timestamp: string
  duration: bigint
  interval: bigint
}
