// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateEventRequestBody } from './CreateEventRequestBody'

export type CreateManyEventsRequestBody = {
  events: Array<CreateEventRequestBody>
}
