// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ServiceMultiPersonOptions } from "./ServiceMultiPersonOptions";

export type CreateServiceRequestBody = { metadata?: JsonValue, multiPerson: ServiceMultiPersonOptions | null, };
