// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for searching on a date time
 */
export type DateTimeQuery = {
  /**
   * Optional "greater than or equal" query (UTC)
   */
  gte: Date
  /**
   * Optional "less than or equal" query (UTC)
   */
  lte: Date
}
