// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for searching on a date time
 */
export type DateTimeQuery = {
  /**
   * Optional "equal" query (UTC)
   */
  eq?: Date
  /**
   * Optional "greater than or equal" query (UTC)
   */
  gte?: Date
  /**
   * Optional "less than or equal" query (UTC)
   */
  lte?: Date
  /**
   * Optional "greater than" query (UTC)
   * This is exclusive of the value
   */
  gt?: Date
  /**
   * Optional "less than" query (UTC)
   * This is exclusive of the value
   */
  lt?: Date
}
