// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DateTimeQueryRange = {
  /**
   * "greater than or equal" query (UTC)
   */
  gte?: Date
  /**
   * "less than or equal" query (UTC)
   */
  lte?: Date
  /**
   * "greater than" query (UTC)
   * This is exclusive of the value
   */
  gt?: Date
  /**
   * "less than" query (UTC)
   * This is exclusive of the value
   */
  lt?: Date
}
