// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'

/**
 * Request body for deleting many events (by event_ids and/or by external_ids)
 */
export type DeleteManyEventsRequestBody = {
  /**
   * List of event IDs to delete
   */
  eventIds?: Array<ID>
  /**
   * List of events' external IDs to delete
   */
  externalIds?: Array<string>
}
