// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'

/**
 * Request body for creating an event
 */
export type DeleteManyEventsRequestBody = {
  /**
   * List of event IDs to delete
   */
  eventIds?: Array<ID>
  /**
   * List of events with external IDs to delete
   */
  externalIds?: Array<string>
}
