// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Occurrence of a `CalendarEvent`
 */
export type EventInstance = {
  /**
   * Start time of the event instance (UTC)
   */
  startTime: Date
  /**
   * End time of the event instance (UTC)
   */
  endTime: Date
  /**
   * Whether the event is busy or not
   */
  busy: boolean
}
