// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEvent } from './CalendarEvent'
import type { EventInstance } from './EventInstance'

export type EventWithInstances = {
  event: CalendarEvent
  instances: Array<EventInstance>
}
