// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'

/**
 * Group of calendar events
 */
export type EventGroup = {
  id: ID
  calendarId: ID
  userId: ID
  accountId: ID
  parentId: string | null
  externalId: string | null
  eventIds: Array<ID>
}
