// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'

/**
 * Calendar event object
 */
export type EventGroupDTO = {
  /**
   * UUID of the event
   */
  id: ID
  /**
   * Optional parent event ID
   */
  parentId: string | null
  /**
   * Optional external ID
   */
  externalId: string | null
  /**
   * UUID of the calendar
   */
  calendarId: ID
  /**
   * UUID of the user
   */
  userId: ID
}
