// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarDTO } from "./CalendarDTO";

/**
 * API response for getting calendars by user
 */
export type GetCalendarsByUserAPIResponse = { 
/**
 * List of calendars
 */
calendars: Array<CalendarDTO>, };
