// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarDTO } from './CalendarDTO'

export type GetCalendarsByMetaAPIResponse = { calendars: Array<CalendarDTO> }
