// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarDTO } from './CalendarDTO'
import type { EventWithInstancesDTO } from './EventWithInstancesDTO'

/**
 * API response for getting calendar events
 */
export type GetCalendarEventsAPIResponse = {
  /**
   * Calendar's data
   */
  calendar: CalendarDTO
  /**
   * Events with their instances (occurrences)
   */
  events: Array<EventWithInstancesDTO>
}
