// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters that can be used when getting an event by external ID
 */
export type GetEventsByExternalIdQueryParams = {
  /**
   * Optional flag to include the events that are from a group with the same external ID
   */
  includeGroups?: boolean
}
