// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEventDTO } from './CalendarEventDTO'
import type { EventInstance } from './EventInstance'

/**
 * API response for getting event instances
 */
export type GetEventInstancesAPIResponse = {
  /**
   * Calendar event
   */
  event: CalendarEventDTO
  /**
   * List of event instances (occurrences)
   */
  instances: Array<EventInstance>
}
