// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'

/**
 * Body for getting events for users in a time range
 */
export type GetEventsForUsersInTimeRangeBody = {
  /**
   * List of user IDs
   */
  userIds: Array<ID>
  /**
   * Start time of the interval for getting the events (UTC)
   */
  startTime: Date
  /**
   * End time of the interval for getting the events (UTC)
   */
  endTime: Date
  /**
   * Generate instances of recurring events, default is false
   */
  generateInstances?: boolean
}
