// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutlookCalendar } from './OutlookCalendar'

export type GetOutlookCalendarsAPIResponse = {
  calendars: Array<OutlookCalendar>
}
