// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetServiceBookingSlotsQueryParams = { timezone?: string, duration: number, interval: number, startDate: string, endDate: string, hostUserIds?: string, };
