// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceBookingSlotsDateDTO } from './ServiceBookingSlotsDateDTO'

export type GetServiceBookingSlotsAPIResponse = {
  dates: Array<ServiceBookingSlotsDateDTO>
}
