// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceDTO } from './ServiceDTO'

export type GetServicesByMetaAPIResponse = { services: Array<ServiceDTO> }
