// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";

/**
 * Query parameters for getting user free/busy
 */
export type GetUserFreeBusyQueryParams = { 
/**
 * Start time for the query (UTC)
 */
startTime: Date, 
/**
 * End time for the query (UTC)
 */
endTime: Date, 
/**
 * Optional list of calendar UUIDs to query
 * If not provided, all calendars of the user will be queried
 */
calendarIds: Array<ID> | null, };
