// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoogleCalendarAccessRole } from './GoogleCalendarAccessRole'

export type GoogleCalendarListEntry = {
  id: string
  accessRole: GoogleCalendarAccessRole
  summary: string
  summaryOverride: string | null
  description: string | null
  location: string | null
  timeZone: string | null
  colorId: string | null
  backgroundColor: string | null
  foregroundColor: string | null
  hidden: boolean | null
  selected: boolean | null
  primary: boolean | null
  deleted: boolean | null
}
