// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventInstance } from "./EventInstance";
import type { ID } from "./ID";

/**
 * API response for getting multiple free/busy
 * HashMap<user_id, List of busy events>
 */
export type MultipleFreeBusyAPIResponse = { [key in ID]?: Array<EventInstance> };
