// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'

export type MultipleFreeBusyRequestBody = {
  userIds: Array<ID>
  startTime: Date
  endTime: Date
}
