// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationProvider } from './IntegrationProvider'

/**
 * Request body for creating an OAuth integration
 */
export type OAuthIntegrationRequestBody = {
  /**
   * OAuth code
   */
  code: string
  /**
   * Integration provider
   * E.g. "Google", "Outlook"
   */
  provider: IntegrationProvider
}
