// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutlookCalendarOwner } from './OutlookCalendarOwner'
import type { OutlookOnlineMeetingProvider } from './OutlookOnlineMeetingProvider'

export type OutlookCalendar = {
  id: string
  name: string
  color: string
  changeKey: string
  canShare: boolean
  canViewPrivateItems: boolean
  hexColor: string
  canEdit: boolean
  allowedOnlineMeetingProviders: Array<OutlookOnlineMeetingProvider>
  defaultOnlineMeetingProvider: OutlookOnlineMeetingProvider
  isTallyingResponses: boolean
  isRemovable: boolean
  owner: OutlookCalendarOwner
}
