// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutlookCalendarEventBodyContentType } from './OutlookCalendarEventBodyContentType'

export type OutlookCalendarEventBody = {
  contentType: OutlookCalendarEventBodyContentType
  content: string
}
