// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Round robin algorithm to decide which member should be assigned a
 * `Service Event` when there are multiple members of a `Service`
 */
export type RoundRobinAlgorithm = "availability" | "equalDistribution";
