// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frequency rule for recurring events
 */
export type RRuleFrequency = 'yearly' | 'monthly' | 'weekly' | 'daily'
