// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'
import type { JsonValue } from './serde_json/JsonValue'
import type { ScheduleRule } from './ScheduleRule'

/**
 * A schedule is a set of rules that define when a service is available
 */
export type ScheduleDTO = {
  /**
   * UUID of the schedule
   */
  id: ID
  /**
   * UUID of the user that owns the schedule
   */
  userId: ID
  /**
   * Array of rules for this schedule
   */
  rules: Array<ScheduleRule>
  /**
   * Timezone (e.g. "America/New_York")
   */
  timezone: string
  /**
   * Metadata (e.g. {"key": "value"})
   */
  metadata?: JsonValue
}
