// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduleRuleVariant =
  | { type: 'WDay'; value: string }
  | { type: 'Date'; value: string }
