// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleRuleInterval } from './ScheduleRuleInterval'
import type { ScheduleRuleVariant } from './ScheduleRuleVariant'

export type ScheduleRule = {
  variant: ScheduleRuleVariant
  intervals: Array<ScheduleRuleInterval>
}
