// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEventSort } from './CalendarEventSort'
import type { SearchEventsRequestBodyFilter } from './SearchEventsRequestBodyFilter'

/**
 * Request body for searching events for one user
 */
export type SearchEventsRequestBody = {
  /**
   * Filter to use for searching events
   */
  filter: SearchEventsRequestBodyFilter
  /**
   * Optional sort to use when searching events
   */
  sort?: CalendarEventSort
  /**
   * Optional limit to use when searching events (u16)
   * Default is 200
   */
  limit?: number
}
