// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimeQuery } from './DateTimeQuery'
import type { ID } from './ID'
import type { IdQuery } from './IdQuery'
import type { JsonValue } from './serde_json/JsonValue'

/**
 * Query parameters for searching events
 */
export type SearchEventsRequestBody = {
  /**
   * User ID
   */
  userId: ID
  /**
   * Optional list of calendar UUIDs
   * If not provided, all calendars will be used
   */
  calendarIds: Array<ID> | null
  /**
   * Optional query on parent ID
   */
  parentId: IdQuery | null
  /**
   * Optional query on start time - "lower than or equal", or "great than or equal" (UTC)
   */
  startTime: DateTimeQuery | null
  /**
   * Optional query on end time - "lower than or equal", or "great than or equal" (UTC)
   */
  endTime: DateTimeQuery | null
  /**
   * Optional list of event status
   */
  status: Array<string> | null
  /**
   * Optioanl query on updated at - "lower than or equal", or "great than or equal" (UTC)
   */
  updatedAt: DateTimeQuery | null
  /**
   * Optional list of metadata key-value pairs
   */
  metadata: JsonValue | null
}
