// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimeQuery } from './DateTimeQuery'
import type { ID } from './ID'
import type { IDQuery } from './IDQueryy'
import type { JsonValue } from './serde_json/JsonValue'

/**
 * Query parameters for searching events
 */
export type SearchEventsRequestBody = {
  /**
   * User ID
   */
  userId: ID
  /**
   * Optional list of calendar UUIDs
   * If not provided, all calendars will be used
   */
  calendarIds?: Array<ID>
  /**
   * Optional query on parent ID
   */
  parentId?: IDQuery
  /**
   * Optional query on start time - "lower than or equal", or "great than or equal" (UTC)
   */
  startTime?: DateTimeQuery
  /**
   * Optional query on end time - "lower than or equal", or "great than or equal" (UTC)
   */
  endTime?: DateTimeQuery
  /**
   * Optional list of event status
   */
  status?: Array<string>
  /**
   * Optioanl query on updated at - "lower than or equal", or "great than or equal" (UTC)
   */
  updatedAt?: DateTimeQuery
  /**
   * Optional list of metadata key-value pairs
   */
  metadata?: JsonValue
}
