// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'
import type { JsonValue } from './serde_json/JsonValue'
import type { ServiceResourceDTO } from './ServiceResourceDTO'

export type ServiceWithUsersDTO = {
  id: ID
  users: Array<ServiceResourceDTO>
  metadata?: JsonValue
}
