// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Service object
 */
export type ServiceDTO = { 
/**
 * UUID of the service
 */
id: ID, 
/**
 * Metadata (e.g. {"key": "value"})
 */
metadata?: JsonValue, };
