// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceBookingSlotDTO } from "./ServiceBookingSlotDTO";

export type ServiceBookingSlotsDateDTO = { date: string, slots: Array<ServiceBookingSlotDTO>, };
