// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceResourceDTO } from './ServiceResourceDTO'

export type ServiceResourceResponse = { user: ServiceResourceDTO }
