// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for setting the public JWT key of an account
 */
export type SetAccountPubKeyRequestBody = { 
/**
 * Public JWT key
 */
publicJwtKey: string | null, };
