// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for setting the webhook of an account
 */
export type SetAccountWebhookRequestBody = {
  /**
   * Webhook URL
   */
  webhookUrl: string
}
