// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for searching on a string
 */
export type StringQuery =
  | { eq: string }
  | { ne: string }
  | { exists: boolean }
  | { in: Array<string> }
