// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `TimeSpan` type represents a time interval (duration of time)
 */
export type TimeSpan = { startTime: string; endTime: string; duration: bigint }
