// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time of the day
 */
export type Time = {
  /**
   * Hours for this time (UTC)
   */
  hours: number
  /**
   * Minutes for this time (UTC)
   */
  minutes: number
}
