// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for updating a calendar's settings
 */
export type UpdateCalendarSettings = { 
/**
 * Optional weekday for the calendar
 */
weekStart?: string, 
/**
 * Optional timezone for the calendar (e.g. "America/New_York")
 */
timezone?: string, };
