// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateCalendarSettings } from './UpdateCalendarSettings'

/**
 * Request body for updating a calendar
 */
export type UpdateCalendarRequestBody = {
  /**
   * Calendar settings
   */
  settings: UpdateCalendarSettings
  name: string | null
  /**
   * Name of the calendar
   */
  name?: string
  /**
   * Optional metadata (e.g. {"key": "value"})
   */
  metadata?: Record<string, string>
}
