// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimePlan } from './TimePlan'

export type UpdateServiceUserRequestBody = {
  availability: TimePlan | null
  bufferAfter: bigint | null
  bufferBefore: bigint | null
  closestBookingTime: bigint | null
  furthestBookingTime: bigint | null
}
