// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceMultiPersonOptions } from './ServiceMultiPersonOptions'

export type UpdateServiceRequestBody = {
  metadata: Record<string, string | number | boolean>
  multiPerson: ServiceMultiPersonOptions | null
}
