// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateCalendarSettings } from './UpdateCalendarSettings'
import type { JsonValue } from './serde_json/JsonValue'

/**
 * Request body for updating a calendar
 */
export type UpdateCalendarRequestBody = {
  /**
   * Calendar settings
   */
  settings: UpdateCalendarSettings
  /**
   * Name of the calendar
   */
  name?: string
  /**
   * Optional metadata (e.g. {"key": "value"})
   */
  metadata?: JsonValue
}
