// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for updating a user
 */
export type UpdateUserRequestBody = {
  /**
   * Optional metadata (e.g. {"key": "value"})
   */
  metadata?: Record<string, string>
}
