// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateCalendarSettings } from './UpdateCalendarSettings'

export type UpdateCalendarRequestBody = {
  settings: UpdateCalendarSettings
  metadata?: Record<string, string>
}
