// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from "./ID";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * User object
 */
export type UserDTO = { 
/**
 * UUID of the user
 */
id: ID, 
/**
 * External id
 */
externalId: string | null, 
/**
 * Metadata (e.g. {"key": "value"})
 */
metadata?: JsonValue, };
