// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'

/**
 * User object
 */
export type UserDTO = {
  /**
   * UUID of the user
   */
  id: ID
  /**
   * Metadata (e.g. {"key": "value"})
   */
  metadata: Record<string, string | number | boolean>
}
