// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ID } from './ID'
import type { IntegrationProvider } from './IntegrationProvider'

export type UserIntegration = {
  user_id: ID
  account_id: ID
  provider: IntegrationProvider
  refresh_token: string
  access_token: string
  access_token_expires_ts: bigint
}
